name: odenet_wordnet_de
description: >-
  Library and simple CLI app for Open German WordNet.
version: 1.0.0
repository: https://github.com/yuwash/odenet_wordnet_de

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.3.0
  path: ^1.9.1
  xdg_directories: ^1.1.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - language

executables:
  odenet-wordnet-de: odenet_wordnet_de
